Repository IT4Change/IT4C.dev, pull requests merged in 2023-02, with the labels that each got.

#39 fix(content): wolle profile fixes
  docs/people/wolfgang-huss.md
Labels: bug, enhancement

#36 feat(content): add a profile for Mathias
  .textlintrc.js
  docs/.vuepress/config.js
  docs/images/portrait/ml-portrait.jpg
  docs/index.md
  docs/people/mathias-lenz.md
Labels: enhancement, good first issue

#40 fix(content): refine wolle's profile – collecting
  docs/people/wolfgang-huss.md
Labels: enhancement
