Repository IT4Change/IT4C.dev, pull requests merged in 2023-11, with the labels that each got.

#42 feat(content): history
  .gitignore
  docs/history.md
Labels: enhancement, help wanted

#86 feat(content): replace big logo with black background by small one with transparent …
  docs/.vuepress/config.js
  docs/.vuepress/public/it4c-logo2-clean-bg_alpha-1024x1024.png
  docs/.vuepress/public/it4c-logo2-clean-bg_alpha-128x128.png
  docs/.vuepress/public/it4c-logo2-clean-bg_black-1024x1024.png
  docs/.vuepress/public/it4c-logo2-clean-bg_black-128x128.png
  docs/.vuepress/public/it4c-logo2.png
Labels: enhancement

#90 feat(content): new email-address
  docs/contact.md
Labels: enhancement

#92 fix(content): remove people and projects not maintained yet
  docs/.vuepress/config.js
  docs/index.md
Labels: bug

#93 feat(content): favicon
  docs/.vuepress/public/favicon.ico
Labels: enhancement
