Repository IT4Change/IT4C.dev, pull requests merged in 2025-02, with the labels that each got.

#209 refactor(other): use current nodejs lts version
  .github/workflows/test-build.yml
  .github/workflows/test-lint.yml
  .github/workflows/vuepress-deploy.yml
  .nvmrc
  package-lock.json
  package.json
Labels: enhancement, dependencies

#217 fix(workflow): set required github-token for automerge workflow
  .github/workflows/automerge.yml
Labels: bug, github_actions

#240 feat(content): refine ocelot projekt page
  docs/images/projects/ocelot-newsfeed.png
  docs/projects/ocelot.social.md
Labels: enhancement
